### ISSUE TITLE
Support AP mode for OTG wifi adapters

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#10]
Add AP mode for wpa_supplicant in zynq_pluto_defconfig.
Edit S40network and set defaults for AP mode SSID, IP, etc
...maybe that's all?...

**Comment by unixpunk** [comment]
Not working on 2 usb wifi adapters w/OTG adapter cable, need uart hooked back up to see if hw is even recognized.

**Comment by unixpunk** [comment]
Does anyone have ANY wifi working on the Pluto?  I can't get anything going out of the box...

**Comment by ImDroided** [comment]
On their website they list a few that have been tested.

**Comment by unixpunk** [comment]
Will revisit this when #35 resolved.
