### ISSUE TITLE
Allow updates through the USB mass storage device

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#13]
Right now you can only update manually by using scp to upload the update.zip to the pluto.  Should figure out how to use the mass storage device where the config file resides.

**Comment by unixpunk** [comment]
Added support in buildroot/board/pluto/update.sh - https://github.com/unixpunk/buildroot/commit/103b016a896b07e5ff51585d3967aff775e833a5

This change requires a new image to take effect because update.sh is running early on before we do updates.  Takes effect here - https://github.com/unixpunk/PlutoWeb/commit/2c1b503b7069087b2b06f4749b5f8f0d8118aba7

**Comment by ImDroided** [comment]
Don't do the new image just yet give me a little bit to upload the new website so it's included

**Comment by unixpunk** [comment]
That commit I listed was the new image.  I'll make a new one whenever ready, after the settings.txt integration probably.

**Comment by unixpunk** [comment]
Works for me.
