### ISSUE TITLE
Allow persistent/changes via config file on mass storage device

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#14]
This is referring to the config file you see on the 'drive' that shows up when the pluto is plugged in via USB.  We should be able to r/w from that file, somehow?

**Comment by ImDroided** [comment]
Pretty sure we can see that drive on the Pluto.

**Comment by unixpunk** [comment]
This needs to become part of a much larger project to rewrite how we handle the writing of variables to nvram as well as integration of PlutoWeb-specific variables into the config.txt file.
