### ISSUE TITLE
edit settings script

### ISSUE THREAD

**Issue by ImDroided** [unixpunk/PlutoWeb#15]
Can you edit your script to include a no flag for all yes or no options i.e write to nvram, autoupdate....... This will make the web CGI script work for everything. Currently it wants a flag for all settings and this would be the easiest fix.

**Comment by unixpunk** [comment]
https://github.com/unixpunk/PlutoWeb/commit/6c728538745e4c5b85cc60ecc5ee49a9ee9cb2e8 - Done.  /bin/settings.sh now requires a y (lowercase) after both -E and -W, so the only option that doesn't require an additional argument is now -i for interactive, which we don't use anyway.  i.e., /bin/settings.sh -c 101100000 -s 101100000 -W y

I didn't create a new update.zip.  Once you make your changes to the www, run buildzip.sh and include update.* in the commit with your www change.

**Comment by ImDroided** [comment]
ok so I can now pass either a y or n for those settings? basically if no is selected it will pass a n or if yes is it will pass a y. the form submission to the cgi script always has these.

**Comment by ImDroided** [comment]
if it isnt like that maybe just add a if statement that does nothing if a n is received.

**Comment by unixpunk** [comment]
you can pass whatever you want, it only cares if it sees a y.  y = do work, anything else = do nothing.  So n is fine to send when you don't want it to erase or write.

**Comment by unixpunk** [comment]
OK this works now, actually tested it this time...
