### ISSUE TITLE
Pass through most other settings for openwebrx and persist in nvram

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#19]
Need to add new variables and pass them into config_webrx.py available to be set in config.txt only, to start with at least.

**Comment by ImDroided** [comment]
What settings are these?

**Comment by unixpunk** [comment]
Whatever is needed so that you can add a plutoweb instance running openwebrx into the list at sdr.hu, so I think API key, grid location antenna info, etc.  Just like the kiwi is listed there, can get these listed too if people wanted.  You can see them in the config.

**Comment by ImDroided** [comment]
Ahhhhh that would be cool

**Comment by unixpunk** [comment]
This is done, only able to save them using config.txt via USB though.  They don't show up in the settings.sh script yet but are listed in /www/settings.txt, you just can't change/save them until I update settings.sh.  Done here: https://github.com/unixpunk/PlutoWeb/commit/22ca1de80e908476800e1f9c9b8a5d38ed758a96 and here: https://github.com/unixpunk/buildroot/commit/b4792646d9b135906e9ec57774934f4c01e2f22b

**Comment by unixpunk** [comment]
You get a chance to try the new image yet?

**Comment by ImDroided** [comment]
Flashed it seems to work fine. I'll look into what was added and edit the
website if needed

**Comment by unixpunk** [comment]
Ah missed that.  Had problems with it showing right in openwebrx too.  That part is fixed but I missed this.

**Comment by unixpunk** [comment]
Ya...I was having problems with this when I put it in...I can't get it to pass over the damn space no matter what quotes/qualifiers I use.  Not sure how to fix this yet or why its even a problem...  Its not just settings.txt, its also not showing right in /root/temp-settings and this is where it needs to be fixed.  Once it shows right in there, then it will work everywhere else too.

**Comment by unixpunk** [comment]
Ugh...looks like I need to redo all of the variable handling when it comes to the fw_printenv stuff...Then it should resolve this crap...

**Comment by unixpunk** [comment]
OK so I think this should be fixed now here: https://github.com/unixpunk/PlutoWeb/commit/4ebe4e6566b93eb95e9ca296177c154eb3f4e945 and in the new img here: https://github.com/unixpunk/PlutoWeb/commit/479aa3bec9e80bb4b714ae51e345405c53977f28 - I'm not sure if the update.zip if good enough, other changes made require rebooting and maybe clearing nvram with settings.sh -E d

Test it out and let me know.  Right now it doesn't include quotes around the location and antenna values in settings.txt, if your stuff needs the quotes, I can add them and push another update.zip.  Also, if you change these settings in config.txt, they will stick.  Make sure you include quotes around them like they are by default.  I have not actually tried registering one with sdr.hu and getting an API key yet.  I'll test that later.

**Comment by unixpunk** [comment]
Don't know why I didn't just add it earlier...I need to insert another variable above receiver_location for receiver_name...

**Comment by ImDroided** [comment]
Lol go ahead and make your changes all I have to do is change the array order which is pretty simple

**Comment by unixpunk** [comment]
OK done - https://github.com/unixpunk/PlutoWeb/commit/43b2592531b0c36a8907beef258919db6aceff76

I don't know if its easy/possible, but you should have your top bar links for openwebrx, dump1090 use the hostname variable and web_port variable for openwebrx :portnumber if you can.  I was able to pull in the hostname in openwebrx, but that's python.
