### ISSUE TITLE
SoapyRemote?

### ISSUE THREAD

**Issue by eblot** [unixpunk/PlutoWeb#25]
Hi,

I cannot get the SoapyRemote to get working on the latest PlutoWeb (v2.7)

Something weird is that the local SoapySDRUtil reports a somewhat unexpected path:

    # /bin/SoapySDRUtil --info
    ######################################################
    ##     Soapy SDR -- the SDR abstraction library     ##
    ######################################################
    
    Lib Version: v0.7.0-gd79a09d3
    API Version: v0.7.0
    ABI Version: v0.7
    Install root: /home/steve/Desktop/SDR/Pluto/staging
    Search path:  /home/steve/Desktop/SDR/Pluto/staging/lib/SoapySDR/modules0.7 (missing)
    No modules found!
    Available factories... No factories found!
    Available converters...

It seems the paths matches the build environment, not the installed one.

The actual search path would rather be: `/lib/SoapySDR/modules0.7`

Soapy tools are rather terse about debugging option switches or even configuration option switches.

Is there any FAQ/HOWTO about SoapySDR remote with PlutoWeb, I guess I'm missing something.

**Comment by eblot** [comment]
It seems the following workaround helps. Being logged (SSH) on PlutoWeb:

    # /bin/SoapySDRUtil --probe
    ######################################################
    ##     Soapy SDR -- the SDR abstraction library     ##
    ######################################################
    
    Probe device
    
    ----------------------------------------------------
    -- Device identification
    ----------------------------------------------------
      driver=null
      hardware=null
    
    ----------------------------------------------------
    -- Peripheral summary
    ----------------------------------------------------
      Channels: 0 Rx, 0 Tx
      Timestamps: NO

Now:

    # create the hardcoded build path
    $ mkdir -p /home/steve/Desktop/SDR/Pluto/staging
    # symlink the missing library path
    $ ln -s /lib /home/steve/Desktop/SDR/Pluto/staging/lib

Then restart SoapySDRServer from either the shell or the web interface, then:

    # /bin/SoapySDRUtil --probe
    ######################################################
    ##     Soapy SDR -- the SDR abstraction library     ##
    ######################################################
    
    Probe device
    [WARNING] SoapySSDPEndpoint failed join group udp://239.255.255.250:1900
      setsockopt(IP_ADD_MEMBERSHIP) [19: No such device]
    
    ----------------------------------------------------
    -- Device identification
    ----------------------------------------------------
      driver=Library version: 0.15 (git tag: v0.15)
      hardware=Backend version: 0.15 (git tag: v0.15)
      ad9361-phy,model=ad9364
      ad9361-phy,xo_correction=39999836
      fw_version=v0.28-12-g9c23-dirty
      hw_model=Analog Devices PlutoSDR Rev.B (Z7010-AD9363)
      hw_model_variant=1
      hw_serial=104400b83991000112002500c51c65acac
      local,kernel=4.9.0-gf457f60
    
    ----------------------------------------------------
    -- Peripheral summary
    ----------------------------------------------------
      Channels: 1 Rx, 1 Tx
      Timestamps: NO
    
    ----------------------------------------------------
    -- RX Channel 0
    ----------------------------------------------------
      Full-duplex: YES
      Supports AGC: NO
      Stream formats: CS8, CS16, CF32
      Native format: CS16 [full-scale=2048]
      Antennas: A_BALANCED
      Corrections: DC removal
      Full gain range: [0, 89] dB
        PGA gain range: [0, 89] dB
      Full freq range: [70, 6000] MHz
        RF freq range: [70, 6000] MHz
      Sample rates: 0.065105, 1, 2, 3, 4, 6, 7, 8, 9, 10 MSps
      Filter bandwidths: 0.2, 1, 2, 3, 4, 6, 7, 8, 9, 10 MHz
    
    ----------------------------------------------------
    -- TX Channel 0
    ----------------------------------------------------
      Full-duplex: YES
      Supports AGC: NO
      Stream formats: CS8, CS16, CF32
      Native format: CS16 [full-scale=2048]
      Antennas: A
      Corrections: DC removal
      Full gain range: [0, 89] dB
        PGA gain range: [0, 89] dB
      Full freq range: [70, 6000] MHz
        RF freq range: [70, 6000] MHz
      Sample rates: 0.065105, 1, 2, 3, 4, 6, 7, 8, 9, 10 MSps
      Filter bandwidths: 0.2, 1, 2, 3, 4, 6, 7, 8, 9, 10 MHz
    
Much better :-)

There is a warning dumped to the error stream:

    [WARNING] SoapySSDPEndpoint failed join group udp://239.255.255.250:1900
      setsockopt(IP_ADD_MEMBERSHIP) [19: No such device]

Looks like a multicast SSDP issue, I'm not sure if it does matter yet.

**Comment by unixpunk** [comment]
Yes, this was a known issue with the available SoapyRemote cmake options at the time this was built.  What is frustrating here is that I already had this fix in place, a symlink exactly as you did but now I can't find it anymore!...  I'm not sure what happened to it, I'll put it back in place and cut another image later today.

**Comment by eblot** [comment]
Ok, thanks.

**Comment by unixpunk** [comment]
Ahh...for some reason I have it in /bin/openwebrx.sh instead of /bin/soapyremote.sh... wth would I do that... :)  So the case here where its broke is when you don't start openwebrx at boot and then switch to soapyremote.  For you, you could just toggle in the plutoweb interface, start openwebrx, then start soapyremote and it will work, this way you don't need to run those commands.

**Comment by eblot** [comment]
Maybe you defined it somewhere in buildroot's `output/target` directory - which gets wiped out?

**Comment by unixpunk** [comment]
Fix here: https://github.com/unixpunk/PlutoWeb/commit/fcfda351c64dab288be342baa4d9bb0570aa9f94
Image to come later.

**Comment by unixpunk** [comment]
Sorry, moved to proper location here instead: https://github.com/unixpunk/PlutoWeb/commit/4630f900d73ad7240beec7ba4580596293fbd90b

**Comment by unixpunk** [comment]
Resolved.  If the device has internet access, auto-updates might fix this on boot without an image flash.

(Better SoapySDR fix: https://github.com/unixpunk/PlutoWeb/commit/230dbeb88201601670da1788ecd806505f795f4c)
(New image up: https://github.com/unixpunk/PlutoWeb/commit/ed4060fc12071ebf291cd72fbd6f2ddefbfae491)

**Comment by unixpunk** [comment]
Oh, and thanks for the help in finding this issue!

**Comment by eblot** [comment]
You're welcome, thanks for fix.

**Comment by unixpunk** [comment]
I'll leave this open pending your testing, if you have a chance to let me know its resolved for your use-case.  Also, on an unrelated note, have you gotten any WiFi devices to work or just Ethernet?  I've had no luck with WiFi at all yet.

**Comment by eblot** [comment]
Ethernet only for now. I did not know there was a wifi mode(?)

I'm kinda busy fighting w/ `qspectrumexplorer` and its dependencies, so I cannot guarantee you to test the latest fix works in the upcoming days, as I'd like to keep the system in a known state, too many issues to work around for now :-)

**Comment by unixpunk** [comment]
Ah ok.  Do you have problems with the Ethernet device suddenly stop working?  Maybe if bumped?  Have seen a lot like this and why I put in the auto-reboot option.  You may want to make sure that's disabled for you if you haven't already.

**Comment by eblot** [comment]
No, no Ethernet issue for now, rock solid (I'm using a hub to power up the device, with 2A capability if it may matters)
