### ISSUE TITLE
SoapySDRServer dies

### ISSUE THREAD

**Issue by eblot** [unixpunk/PlutoWeb#26]
I'm not yet sure whether it is due to a comm issue from a client, or if may die while being idle, but SoapySDRServer dies sometimes (2 times in a 2 hour timeframe for now).

I think it could be useful to restart it automatically.

**Comment by eblot** [comment]
Ok, it looks like something due to the client.

The client in my use case is soapy_power. It is started from qspectrumanalyser which likes to crash. When it crashes, it does not kill the `soapy_power` subprocess it has previously started. That's bad, but the issue with Pluto's SoapySDRServer occurs when `soapy_power` is hard-killed (`kill -9`). Here is the trace which is emitted from the SoapySDRServer server on Pluto's side:

    # /bin/SoapySDRServer --bind
    ######################################################
    ## Soapy Server -- Use any Soapy SDR remotely
    ######################################################
    
    Server version: 0.5.0-gfa71b4e2
    Server UUID: ee6d776f-0f9b-1000-8567-0dbb007f0101
    Launching the server... tcp://0.0.0.0:55132
    Server bound to 0.0.0.0:55132
    Launching discovery server...
    [WARNING] SoapySSDPEndpoint failed join group udp://239.255.255.250:1900
      setsockopt(IP_ADD_MEMBERSHIP) [19: No such device]
    Connecting to DNS-SD daemon...
    [INFO] Avahi version:  avahi 0.7
    [INFO] Avahi hostname: pluto
    [INFO] Avahi domain:   local
    [INFO] Avahi FQDN:     pluto.local
    [INFO] avahi_entry_group_add_service(pluto._soapy._tcp)
    Press Ctrl+C to stop the server
    SoapyServerListener::accept(192.168.2.10:56645)
    SoapyServerListener::accept(192.168.2.10:56646)
    SoapyServerListener::close()
    SoapyServerListener::accept(192.168.2.10:56647)
    SoapyServerListener::handlerLoop() FAIL: SoapyRPCUnpacker::recv(header) FAIL:
    SoapyServerListener::handlerLoop() FAIL: SoapyRPCUnpacker::recv(header) FAIL:
    terminate called without an active exception
    Aborted

I do not think the server should crash at first, but anyway I think Pluto's "should" track this service and restart it after a grace delay.

**Comment by eblot** [comment]
[100% reproducible]

**Comment by eblot** [comment]
Yes it seems to be dead:

    # ps ax | grep Soap
    6532 root     grep Soap

**Comment by eblot** [comment]
Meanwhile:

    while true; do /bin/SoapySDRServer --bind; sleep 0.5; done

:-)

**Comment by unixpunk** [comment]
OK thanks!

**Comment by unixpunk** [comment]
Added: https://github.com/unixpunk/PlutoWeb/commit/944ec56ecfbf4a390b3abb6083183c3b35f5e898
If auto-updates enabled, then reboot and you'll get all the fixes: https://github.com/unixpunk/PlutoWeb/commit/6ed0b73e773b86f7bc0c0bd29065200bf40e83de

No image yet, maybe you'll find more for me...  :)

**Comment by unixpunk** [comment]
Also, @eblot please link your SoapyRemote issue URL here as well for tracking when you open it.

**Comment by eblot** [comment]
Yes I would have cross-linked it.

Here it is: https://github.com/pothosware/SoapyRemote/issues/44

**Comment by eblot** [comment]
Is it possible to add GDB to a test image? or the pointer(s) to build a buildroot image - if I get some time to rebuilt it myself. Thanks.

**Comment by unixpunk** [comment]
@eblot I had to adjust some other things in the firmware to get gdb to fit, so I'm not sure if everything will work 100% on it yet, but I do have one with gdb.  I'd rather not push it here, so if you have somewhere I can upload it, I'll do that tonight.

**Comment by unixpunk** [comment]
Here is a dfu image you can test with gdb on it.  Hope that helps!  https://mega.nz/#!3qwHEbSB!ZFpWbR3dvcCk1Pi_fuqJ6uat23w16y8q-fBZBb8o2rY

**Comment by eblot** [comment]
Thanks for the image.

I thought I could reflash the DFU file this way:

    $ dfu-util -a firmware.dfu -D ~/Downloads/pluto.dfu

But something goes wrong:

    $ dfu-util -a firmware.dfu -D ~/Downloads/pluto.dfu
    dfu-util 0.9
    
    Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
    Copyright 2010-2016 Tormod Volden and Stefan Schmidt
    This program is Free Software and has ABSOLUTELY NO WARRANTY
    Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
    
    Match vendor ID from file: 0456
    Match product ID from file: b673
    Deducing device DFU version from functional descriptor length
    dfu-util: No DFU capable USB device available

Should I reflash boot.dfu first?
Pluto is up and running (seen on USB, Ethernet available)

**Comment by eblot** [comment]
Same issue using Debian (vs. macOS):
Pluto device appears as a USB device

      eblot@vglencoe:~$ lsusb
      ...
      Bus 001 Device 005: ID 0456:b673 Analog Devices, Inc.
      ...

But dfu-util does not detect it as a valid DFU
    
      eblot@vglencoe:~$ sudo dfu-util -l
      dfu-util 0.9
    
      Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
      Copyright 2010-2016 Tormod Volden and Stefan Schmidt
      This program is Free Software and has ABSOLUTELY NO WARRANTY
      Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

The weird thing is that I've installed the regular PlutoWeb distribution with DFU util (as the other method left the device unresponsive), and I had to reflash `boot.dfu` after that...
I'm not sure what to do from here.

**Comment by eblot** [comment]
Ok, got it: https://wiki.analog.com/university/tools/pluto/users/customizing

I would suggest to add this to the flashing instruction, as for some reason, my device add DFU mode enabled, but this setting got wiped out at some stage - I did not changed it myself.

**Comment by eblot** [comment]
BTW I found `gdbserver` on v2.8, not `gdb` itself :-(

**Comment by eblot** [comment]
To sum up for now:
 - gdbserver dies because SIGABRT is triggered by the debugged SoapySDRServer
 - I'm not sure which GDB version I should use on the host:
    - native gdb? (I'm running macOS as my dev. platform)
    - native gdb for linux?
    - gdb for arm? (`arm-none-eabi-gdb` is available on macOS & Debian)
    - gdb for arm for linux? (`arm-linux-eabigdb` or the like), to be rebuilt from scratch, only from a Linux host...
 - `arm-none-eabi-gdb` (the one I have) I guess will not be able to interpret info from a Linux remote
    - I can catch the `SIGABRT` signal but I do not get any backtrace from this point.
 - native `gdb` running in a Linux VM fails to communicate with the remote target, with a weird comm issue:

        Remote 'g' packet reply is too long: 00000000000000000000000000000000000000000000000...

  This seems to be related to the CPU mismatch, as `arm-none-eabi-gdb` does not exhibit this symptom.
 
I'm afraid I do not have enough time to explore all the nasty combinations of GNU tools. :-( If you can get the real "gdb" (not the server version which adds its own issues) on Pluto let me know. Or if I get enough spare time, I'll try to rebuilt it.

**Comment by eblot** [comment]
Ok, I got it.
I've build a buildroot env. for Pluto, including GDB and scp'ied it (with the dynamic loader as I used MUSL-C library) to my Pluto. I got a full backtrace.

I'll copy it to https://github.com/pothosware/SoapyRemote/issues/44

**Comment by eblot** [comment]
New ticket for SoapyPlutoSDR plugin: https://github.com/jocover/SoapyPlutoSDR/issues/11

**Comment by unixpunk** [comment]
@eblot Thanks again for the help on this, for now the while loop should take care of this.  Its in the current update.zip and will also be in the next image I build.  I also watch the SoapyPlutoSDR project so I'll know when a fix is made and will incorporate it here when possible.

**Comment by eblot** [comment]
You're welcome. I agree, let's wait for a proper fix in the plugin.

I think a nice addition to the PlutoWeb home page would be to have a status about the up-and-running daemon(s), such as a readonly check box or a green/red flag, to get a status about the active features.

I would suggest to have a look at the `start-stop-daemon` helper (already available on buildroot), it makes easy to manage daemon stop/start, and to track their status through a PID number, and avoid spawning several at once.

Fully off-topic: could you recommend me a very simple tool to check if the SoapySDR sends the proper values? I fight with `qspectrumanalyser` and `soapy_power`, fixed several issues, but I'm pretty sure the data gets out-of-sync. The simplest tool the better. Thanks.

**Comment by unixpunk** [comment]
Thanks for the suggestion, I agree.  @ImDroided is the web guy, he and I haven't had much time to talk about/focus on the webUI lately.

RE the soapy stuff, I'm not sure.  The only way I ever use SoapyRemote is with CubicSDR.  That works fine for me unless sample rate is too high, then its choppy.

**Comment by ImDroided** [comment]
Sorry guys about my lacking on the webui lately I will be away for work
this week so I should have time to mess with it at my hotel since I won't
have the family to deal with. Someone make a ticket with all that needs to
be added or changed and I'll try to tackle it this week coming up.
