### ISSUE TITLE
Leantrx power

### ISSUE THREAD

**Issue by G0MJW** [unixpunk/PlutoWeb#27]
Lean TRX has a power parameter (--power)  but it isn't available on the DATV TX web settings.

**Comment by unixpunk** [comment]
Can you test each of these options and let me know which one seems to work better for you?  SSH to the pluto but stay on the dvb tx page and stop the sdr:  

sed -i 's/-4/89/' /www/cgi-bin/leantrx/dvbtx.cgi
Then enable the SDR again and see how it looks.

Then run:
sed -i 's/--power 89/--agc/' /www/cgi-bin/leantrx/dvbtx.cgi
Then disable/enable the sdr and see how that option is instead.

**Comment by G0MJW** [comment]
They both look the same which is interesting. All -20dBm. 

I found another issue causing a problem. I have found the only way to make this decode is to set the RRC Rejection to 0 rather than the default 10.

**Comment by unixpunk** [comment]
You can try to change --power to 0, that one might be the right option, then change it to 10 and see the difference.  I don't know what the waterfall should look like but in testing mine, I see a drastic shape difference between power at 0 and at 10.

**Comment by unixpunk** [comment]
https://github.com/unixpunk/PlutoWeb/commit/c2ff4c9384173e24ba21a6bc9a169d55423272c1 Set power from -4 to 0 and rrc_rej from 10 to 0.  Let me know if you're able to find the optimal settings and I'll change them in another update.zip.

**Comment by unixpunk** [comment]
@G0MJW I'll close this for now unless you have any other update/request related to changing command line options, etc.  Thanks for the assist!

**Comment by G0MJW** [comment]
Sorry for the silence, I have been travelling and without email access for
the last couple of weeks.

Was I supposed to be testing something?

**Comment by unixpunk** [comment]
No prob, just mean that if you wanted a different value here or other values in the cmd line changed, let me know in a new issue.
