### ISSUE TITLE
Change updatewatch.sh so it processes manually uploaded updates even if auto-updates disabled

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#29]
Change updatewatch.sh so it processes manually uploaded updates even if auto-updates disabled.  This prevents the need to SSH and run updatewatch.sh manually.

**Comment by ImDroided** [comment]
This is not working for me. upload zip through web and it doesnt do anything. worked fine before.

**Comment by unixpunk** [comment]
ya, im looking for the other commit now...i fixed it though...just after the last image and version tag.  If you flash the latest, then just turn off auto-updates and reboot.  Then manual uploads will work again.

**Comment by unixpunk** [comment]
https://github.com/unixpunk/PlutoWeb/commit/69ffb7c5642f416eb5cb6b11bd072d8a8ccbbbc6 That's one of many I forgot to push..  I'm building a new image and update zip now.

**Comment by ImDroided** [comment]
ok cool. then after my changes you can build a new image with everything,

**Comment by unixpunk** [comment]
One is already building now, I'm going to upload and tag it to 2.9.  We'll make the web changes part of 3.0.

**Comment by unixpunk** [comment]
New image up with this fixed: https://github.com/unixpunk/PlutoWeb/commit/db5fbd744ca9ebf564e75270daf97c5000e07ab5

**Comment by unixpunk** [comment]
This works solid both ways now, on or off.  Tested on latest build: https://github.com/unixpunk/PlutoWeb/commit/87a81d130f15db56f61e8dc845c947ed62f33dd1
