### ISSUE TITLE
Switch from zip to gzip or bzip2

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#34]
Winner is gzip.

**Comment by ImDroided** [comment]
What about tar? What is included in the image by default or whats the smallest?

**Comment by unixpunk** [comment]
Ya, will be tar+gzip because the fw has bunzip2 but not bzip2 while gzip has -d so it can do both compress/uncompress.  This way you can zip up your running stuff into an update.tgz if you wanted, you can't with bzip2.

**Comment by unixpunk** [comment]
First attempt, let's see what I forgot to change: https://github.com/unixpunk/PlutoWeb/commit/ba7628ca4315b73218dbca2f7dfaf241aa24b0e6 and https://github.com/unixpunk/buildroot/commit/1868ef7fdd40c753f6945694514464ac6f18c80b
FW build yet to come.

**Comment by unixpunk** [comment]
Latest build: https://github.com/unixpunk/PlutoWeb/commit/87a81d130f15db56f61e8dc845c947ed62f33dd1

**Comment by unixpunk** [comment]
Seems to work for me with latest update.tgz from web and also when dumped locally.
