### ISSUE TITLE
add LearnTRX option to settings.sh

### ISSUE THREAD

**Issue by ImDroided** [unixpunk/PlutoWeb#36]
maybe add a LearnTRX flag to settings.sh so in the future if we can ever pass stuff along to it might make things a bit easier. then I can call that with the CGI file instead of the none flag

**Comment by ImDroided** [comment]
this may work the best because then you can work the link into the output just like openwebrx and dump1090

**Comment by unixpunk** [comment]
done: https://github.com/unixpunk/PlutoWeb/commit/fe3bb27921d47e73b19b61df8697587329f62386

**Comment by unixpunk** [comment]
I don't think this change made it into the image itself, not sure on the timing.  Go with it anyway.  You can test it by running: mv /etc/init.d/S96none /etc/init.d/S96leantrx

Then test your buttons and things.  It won't say anything about leantrx in the output, but you'll know things will work on the next build.

**Comment by LamaBleu** [comment]
Hi, just reflashed, performed some tests.
Manual update seems ok copying the file to USB mass storage and unmounting.
Leantrx is working perfectly, I can launch openwebrx, exit then click SoapyRemote button, and go to leantrx without issue.
Just one thing :the message related to leantrx URL access is not displayed, please [see my comment](https://github.com/unixpunk/PlutoWeb/commit/50d6de432dadcfc6e0cf10dff49c23cb0b3e0a45#r30309044) about /etc/init.d/S9SoapyRemote file
thanks again ;)

**Comment by unixpunk** [comment]
@LamaBleu Noted and resolved in one way or another on the next build yet to come. https://github.com/unixpunk/PlutoWeb/commit/fe3bb27921d47e73b19b61df8697587329f62386 https://github.com/unixpunk/PlutoWeb/commit/886e853fc5a9aab1bd128489c5ad255b67851868 https://github.com/unixpunk/PlutoWeb/commit/83a48d823b4e055756585a3684072de53b4adc62

**Comment by unixpunk** [comment]
Latest build: https://github.com/unixpunk/PlutoWeb/commit/87a81d130f15db56f61e8dc845c947ed62f33dd1

**Comment by unixpunk** [comment]
Latest commits and update.tgz look good.
