### ISSUE TITLE
edit file to change google map API key in dump1090

### ISSUE THREAD

**Issue by fllay** [unixpunk/PlutoWeb#38]
I can edit a file to change the API key but I cannot save it. It will go back to the original value after reboot. Any option to change to key?

**Comment by unixpunk** [comment]
Not currently, I would have to add that functionality.  I would rather someone help convert it over to a more open map system that doesn't require an API key that isn't even provided for free to 'just anyone' anymore...  https://github.com/unixpunk/PlutoWeb/issues/33 - Wanna help with that effort instead?  :)

**Comment by LamaBleu** [comment]
Hi, I tried to cross compile the dump1090 version from @Mictronics two months ago.
No luck so far. I can't get the json file, and interactive mode is not working on console.
For more details have a look here : https://github.com/Mictronics/dump1090/issues/7
However I suspect my environment (Ubuntu 16.04 LTS) ... and compilation should work on a more decent computer.
But I also realized the Mictronics version take too much space for the Pluto firmware flash.

So I restarted from scratch, using the original and light version, proven to work on pluto : https://github.com/PlutoSDR/dump1090

I was able to get dump1090 working, and get the aircraft json files. I replaced the googlemaps by OL3, was able to pinpoint my location on the map, and display the aircraft.json file on the screen. So far is not so bad.
TODO : 
- display aircrafts from the json file on the map (have to create a new layer).
- display aircraft list
- implement autorefresh.
Please see my actual result as attachment. 
I share the gmap.html file if someone is interested to work on this. Sorry but I  don't have spare time at this moment for this even if it's really interesting :)  And totally it's out of my skills ;)

![dump1090-pluto](https://user-images.githubusercontent.com/26578895/50541303-00a68a80-0ba3-11e9-8ce0-e77743fa5789.png)
[ol3.zip](https://github.com/unixpunk/PlutoWeb/files/2716645/ol3.zip)

**Comment by unixpunk** [comment]
Thanks, @LamaBleu !  I'll take a look.  I'm hoping to have time today to rebuild my xilinx stuff on this new system so I can start making changes again.  Guess we should probably update to 0.29 as well. (more xilinx fun)
