### ISSUE TITLE
Create OpenWebRx "Pre-sets"

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#41]
Create pre-sets for different settings in OpenWebRx.  

Last used pre-set will be retained if written to nvram.

It will act as an override to plutoweb.conf during run-time only and will not actually modify the variables or nvram.

Will need a new variable created that can be written to nvram, "openwebrx_override".  It will always have an integer 0-4 with 0 being default.

Will need a drop-down menu on the main page and settings screen with 5 options:
0- Pre-set Overrides Off
1- 100ksps - 15 Users Max
2- 300ksps - 7 Users Max
3- 900ksps - 2 Users Max
4- 1.5msps - 1 User Only

The change will take effect when clicking start on the main page or save settings on the settings page.

The $openwebrx_override value will be on line 26 in settings.txt.

**Comment by unixpunk** [comment]
Variable done: https://github.com/unixpunk/PlutoWeb/commit/8fbf86496d8e255506c3198fd682d2446dfbabc4

**Comment by unixpunk** [comment]
Can change pre-sets with /bin/settings.sh -o [0-4] - https://github.com/unixpunk/PlutoWeb/commit/116e2e96a71a39c9fc34f080c3fb006337078333

**Comment by unixpunk** [comment]
We may have fewer pre-sets needed since adjusting the fft quality has little effect on CPU usage now that we're using hard floats.  May only need 2 or 3 pre-sets.

**Comment by ImDroided** [comment]
I'll have to add this to the webui

**Comment by unixpunk** [comment]
OK, all pre-set work done aside from web stuff.  https://github.com/unixpunk/PlutoWeb/commit/1908e554b2782fca8d89c948c93a2cf50f54f8f5 and https://github.com/unixpunk/PlutoWeb/commit/8744e094eb4da08fe95ebc889ebef1e41163d8b3

**Comment by ImDroided** [comment]
Code is done need to test before I commit.

**Comment by ImDroided** [comment]
https://github.com/unixpunk/PlutoWeb/commit/58382d6f886ac57c7f01dd577517e0baad178d66

Needs testing

**Comment by unixpunk** [comment]
Worksforme Thanks!
