### ISSUE TITLE
Question:  Will the latest PlutoWeb kernel work with IIO?

### ISSUE THREAD

**Issue by glangsto** [unixpunk/PlutoWeb#46]
This is more of a question than an issue.   I've successfully run some python on the early January 2019 PlutoWeb kernel.   The new capabilities are great.  

However I'm having some trouble running some of the interfaces with PlutoSDR and Gnuradio companion graphs.   Which, if any, of the Gnuradio-companion source and sink blocks
work with this version of the PlutoSDR kernel?

Thanks for all your effort.

Best regards
Glen

**Comment by unixpunk** [comment]
I've not messed with gnuradio at all so I have no idea.  Do you mean that you have trouble with gnuradio running on your PC?  Have you made sure to stop any running apps by selecting either SoapyRemote or LeanTRX from the webUI or settings.sh -r none from SSH?  You can set the default as well so you don't have to do this each boot, settings.sh -r none -W y -or- set the autostart value in config.txt to none and eject.  If you can provide specifics, I'll do what I can to fix it.  Can you also test flashing the .30 version directly from the plutosdr-fw repo to make sure its not broke upstream?

**Comment by glangsto** [comment]
Hi
Thanks for your very quick response.   Yes I've got Odroid XU4 and a Raspberry PI 3B+,
both Ubuntu 18.04 LTS +/- some Raspian additions,
that were running gnu radio companion Pluto SDR Source blocks  (and kernel v0.29) fine, 
talking with the Pluto SDR.

Then with the new, improved kernel, the Gnuradio graphs did not work, but possibly
I did not turn off the boot-up processing done by the kernel.   Unfortunately,
I can not test your suggestion until a week from today.   I'll double check that
boot up processing was stopped, before starting gnu radio.

 Thanks again.   PS I did get event capture running well in gnu radio. The python code
and test graphs are available via: git clone https://www.github.com/glangsto/gr-nsf
I'm working on a port to C++,- to get the designs to work at a faster rate than 1MHz.

**Comment by unixpunk** [comment]
Were you able to confirm if this worked for you after disabling the default autostart of openwebrx (and setting the value to none) in the config.txt and rebooting?

**Comment by glangsto** [comment]
Hi

Thanks for following up on my questions.   The last time I tried (about 1.5 months ago), I
could use python and applications on PlutoSdr, but I could no longer
run Gnuradio programs on  my laptop and talk to the PlutoSdr to get data.

I will try again this weekend.  

 event capture running in C++. We’ve put the code (both C++ and Python Versions)
on GitHub:

https://github.com/glangsto/gr-detect_cc/ <https://github.com/glangsto/gr-detect_cc/>

This seems to be working well.  I’ve just improved the documentation.

Best regards

Glen

**Comment by unixpunk** [comment]
I commented in reply to this on the other issue regarding your code.  I'm going to assume that if you stop any of the apps using the radio that gnuradio will then work fine since other tools using iio do.
