### ISSUE TITLE
.local domain use

### ISSUE THREAD

**Issue by roelandjansen** [unixpunk/PlutoWeb#57]
I have not tested/used your software yet. I still have plans for that.

I however noticed the use of pluto.local and I would suggest to change that into something else as .local use has some dawbacks. (.invalid could be better).

https://en.wikipedia.org/wiki/.local

**Comment by unixpunk** [comment]
Thanks for feedback, agreed not the best choice.  The default plutosdr-fw uses pluto.local, I don't override it.  You can try entering an FQDN for the hostname in config.txt and save/eject and see if after a reboot things resolve to the new domain, but its mostly avahi/mdns handling all this.  If there's a change to be made to the avahi config, I'd be open to it.  Hope that helps.
