### ISSUE TITLE
Since this is really all about PlutoWeb now, should we rename the repo?

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#6]
What do you think?  Rename it?  I just called it PlutoWeb without much thought, have an idea for a better name?

**Comment by ImDroided** [comment]
Yea sounds like a good idea. but if you have a lot of pluto stuff then maybe leave it?

**Comment by unixpunk** [comment]
Needs more planning since a lot of scripts I use today outside of the git repo look for this path.

**Comment by ImDroided** [comment]
PlutoWeb works just fine and is straight to the point

**Comment by unixpunk** [comment]
Done, renamed to PlutoWeb.  Looks like the original PlutoSDR address still works, just don't know for how long.  I would do a git pull and git commit and see if you have any changes to push.  Push those changes with the old PlutoSDR folder, then cd .. and clone the new PlutoWeb git address and start your work again from there.
