### ISSUE TITLE
Web page updates

### ISSUE THREAD

**Issue by unixpunk** [unixpunk/PlutoWeb#9]
1. Does the settings popup pull the current settings or just use some pre-defined defaults?  Can you make it pull the current settings each time if it doesn't already?  Not sure how you want to do that, you could cat /root/temp-settings and pull out the values or run /bin/readsettings.sh and pull them from the output.  I can help where needed using awk or whatever to strip out the unnecessary stuff.

2. The auto-reboot was changed from 24 hours to 12 hours since I still see if randomly going dark.  I need to hook back up the UART to see what the deal is when OTG goes dark.  For now, take out the '24h' from the settings page for the reboot and just leave it without a time range for now.

**Comment by ImDroided** [comment]
The popup uses the defaults all the time. I will have to try a different approach and have that in a separate CGI script and have it call that script instead of display the hidden content. This is where PHP and SQL would be awesome. This should be easy enough ill mess with it when I get a chance.

**Comment by unixpunk** [comment]
Ah OK.  If your CGI can run /root/temp-settings, it will load the current settings into environment variables.  Can CGI read the environment variables of the shell its running from?  You'd have to run the /root/temp-settings with a . in front so it runs in the current environment and doesn't spawn a new one.  ". /root/temp-settings".  That will export all the current settings into variables for reading.  Or you could come up with another way to just read that file and pull out the variables, ignoring the export commands.  If this is a problem, I can figure out how to redo this file.  Putting exports in there and making it executable was the easiest route at the time.

**Comment by unixpunk** [comment]
I wrapped your changes into the update.zip.  Looks good, I like the links up top.  Not sure if I should see an icon for dump1090 down in the body of the page but I just see green text that just says dump1090 next to the header for Dump1090.

Also, you can create that zip as well just by running the buildzip.sh script there.  It takes care of it all, then its part of the commit, or its own commit.  Then anyone with auto-update enabled will get it next boot, which by default will be within 12 hours.

**Comment by unixpunk** [comment]
Good to go.
